---
- name: Provision Load Balancer
  hosts: lb1.demo.toal.ca

  tasks:
    - name: Create a pool
      f5networks.f5_modules.bigip_pool:
        lb_method: ratio-member
        name: web
        slow_ramp_time: 120
      delegate_to: localhost
